`timescale 1ns/1ps

module top_mkBsvTopWithResetBuffer (
    input  wire         CLK,
    input  wire         RST_N,
    input  wire         CLK_ftileClk,
    output wire         RST_N_partitionReset,
    output wire         RST_N_buffered_long,
    input  wire [1023:0] rtilePcieAdaptorRxRawIfc_data,
    input  wire [511:0]  rtilePcieAdaptorRxRawIfc_hdr,
    input  wire [3:0]    rtilePcieAdaptorRxRawIfc_sop,
    input  wire [3:0]    rtilePcieAdaptorRxRawIfc_eop,
    input  wire [3:0]    rtilePcieAdaptorRxRawIfc_hvalid,
    input  wire [3:0]    rtilePcieAdaptorRxRawIfc_dvalid,
    input  wire [11:0]   rtilePcieAdaptorRxRawIfc_bar,
    input  wire [11:0]   rtilePcieAdaptorRxRawIfc_empty,
    input  wire [2:0]    rtilePcieAdaptorRxRawIfc_hcrdt_init_ack,
    input  wire [2:0]    rtilePcieAdaptorRxRawIfc_dcrdt_init_ack,
    output wire          rtilePcieAdaptorRxRawIfc_ready,
    output wire [2:0]    rtilePcieAdaptorRxRawIfc_hcrdt_init,
    output wire [2:0]    rtilePcieAdaptorRxRawIfc_hcrdt_update,
    output wire [5:0]    rtilePcieAdaptorRxRawIfc_hcrdt_update_cnt,
    output wire [2:0]    rtilePcieAdaptorRxRawIfc_dcrdt_init,
    output wire [2:0]    rtilePcieAdaptorRxRawIfc_dcrdt_update,
    output wire [11:0]   rtilePcieAdaptorRxRawIfc_dcrdt_update_cnt,
    input  wire [2:0]    rtilePcieAdaptorTxRawIfc_hcrdt_init,
    input  wire [2:0]    rtilePcieAdaptorTxRawIfc_hcrdt_update,
    input  wire [5:0]    rtilePcieAdaptorTxRawIfc_hcrdt_update_cnt,
    input  wire [2:0]    rtilePcieAdaptorTxRawIfc_dcrdt_init,
    input  wire [2:0]    rtilePcieAdaptorTxRawIfc_dcrdt_update,
    input  wire [11:0]   rtilePcieAdaptorTxRawIfc_dcrdt_update_cnt,
    input  wire          rtilePcieAdaptorTxRawIfc_ready,
    output wire [2:0]    rtilePcieAdaptorTxRawIfc_hcrdt_init_ack,
    output wire [2:0]    rtilePcieAdaptorTxRawIfc_dcrdt_init_ack,
    output wire [511:0]  rtilePcieAdaptorTxRawIfc_hdr,
    output wire [1023:0] rtilePcieAdaptorTxRawIfc_data,
    output wire [3:0]    rtilePcieAdaptorTxRawIfc_sop,
    output wire [3:0]    rtilePcieAdaptorTxRawIfc_eop,
    output wire [3:0]    rtilePcieAdaptorTxRawIfc_hvalid,
    output wire [3:0]    rtilePcieAdaptorTxRawIfc_dvalid,
    input  wire [1023:0] ftileMacAdaptorRxRawIfc_data,
    input  wire          ftileMacAdaptorRxRawIfc_valid,
    input  wire [15:0]   ftileMacAdaptorRxRawIfc_inframe,
    input  wire [47:0]   ftileMacAdaptorRxRawIfc_eop_empty,
    input  wire [15:0]   ftileMacAdaptorRxRawIfc_fcs_error,
    input  wire [31:0]   ftileMacAdaptorRxRawIfc_error,
    input  wire [47:0]   ftileMacAdaptorRxRawIfc_status_data,
    output wire          ftileMacAdaptorRxRawIfc_ready,
    input  wire          ftileMacAdaptorTxRawIfc_ready,
    output wire [1023:0] ftileMacAdaptorTxRawIfc_data,
    output wire          ftileMacAdaptorTxRawIfc_valid,
    output wire [15:0]   ftileMacAdaptorTxRawIfc_inframe,
    output wire [47:0]   ftileMacAdaptorTxRawIfc_eop_empty,
    output wire [15:0]   ftileMacAdaptorTxRawIfc_error,
    output wire [15:0]   ftileMacAdaptorTxRawIfc_skip_crc
);

    rtile_reset_output_buffer u_reset_buf (
        .clk            (CLK),
        .i_reset_n      (RST_N),
        .o_short_reset_n(RST_N_partitionReset),
        .o_long_reset_n (RST_N_buffered_long)
    );

    mkBsvTop u_bsv_top (
        .CLK_ftileClk                       (CLK_ftileClk),
        .RST_N_ftileRst                     (1'b1),
        .RST_N_partitionReset               (RST_N_partitionReset),
        .CLK                                (CLK),
        .RST_N                              (RST_N_buffered_long),
        .rtilePcieAdaptorRxRawIfc_data      (rtilePcieAdaptorRxRawIfc_data),
        .rtilePcieAdaptorRxRawIfc_hdr       (rtilePcieAdaptorRxRawIfc_hdr),
        .rtilePcieAdaptorRxRawIfc_sop       (rtilePcieAdaptorRxRawIfc_sop),
        .rtilePcieAdaptorRxRawIfc_eop       (rtilePcieAdaptorRxRawIfc_eop),
        .rtilePcieAdaptorRxRawIfc_hvalid    (rtilePcieAdaptorRxRawIfc_hvalid),
        .rtilePcieAdaptorRxRawIfc_dvalid    (rtilePcieAdaptorRxRawIfc_dvalid),
        .rtilePcieAdaptorRxRawIfc_bar       (rtilePcieAdaptorRxRawIfc_bar),
        .rtilePcieAdaptorRxRawIfc_empty     (rtilePcieAdaptorRxRawIfc_empty),
        .rtilePcieAdaptorRxRawIfc_hcrdt_init_ack(rtilePcieAdaptorRxRawIfc_hcrdt_init_ack),
        .rtilePcieAdaptorRxRawIfc_dcrdt_init_ack(rtilePcieAdaptorRxRawIfc_dcrdt_init_ack),
        .rtilePcieAdaptorRxRawIfc_ready     (rtilePcieAdaptorRxRawIfc_ready),
        .rtilePcieAdaptorRxRawIfc_hcrdt_init(rtilePcieAdaptorRxRawIfc_hcrdt_init),
        .rtilePcieAdaptorRxRawIfc_hcrdt_update(rtilePcieAdaptorRxRawIfc_hcrdt_update),
        .rtilePcieAdaptorRxRawIfc_hcrdt_update_cnt(rtilePcieAdaptorRxRawIfc_hcrdt_update_cnt),
        .rtilePcieAdaptorRxRawIfc_dcrdt_init(rtilePcieAdaptorRxRawIfc_dcrdt_init),
        .rtilePcieAdaptorRxRawIfc_dcrdt_update(rtilePcieAdaptorRxRawIfc_dcrdt_update),
        .rtilePcieAdaptorRxRawIfc_dcrdt_update_cnt(rtilePcieAdaptorRxRawIfc_dcrdt_update_cnt),
        .rtilePcieAdaptorTxRawIfc_hcrdt_init(rtilePcieAdaptorTxRawIfc_hcrdt_init),
        .rtilePcieAdaptorTxRawIfc_hcrdt_update(rtilePcieAdaptorTxRawIfc_hcrdt_update),
        .rtilePcieAdaptorTxRawIfc_hcrdt_update_cnt(rtilePcieAdaptorTxRawIfc_hcrdt_update_cnt),
        .rtilePcieAdaptorTxRawIfc_dcrdt_init(rtilePcieAdaptorTxRawIfc_dcrdt_init),
        .rtilePcieAdaptorTxRawIfc_dcrdt_update(rtilePcieAdaptorTxRawIfc_dcrdt_update),
        .rtilePcieAdaptorTxRawIfc_dcrdt_update_cnt(rtilePcieAdaptorTxRawIfc_dcrdt_update_cnt),
        .rtilePcieAdaptorTxRawIfc_ready     (rtilePcieAdaptorTxRawIfc_ready),
        .rtilePcieAdaptorTxRawIfc_hcrdt_init_ack(rtilePcieAdaptorTxRawIfc_hcrdt_init_ack),
        .rtilePcieAdaptorTxRawIfc_dcrdt_init_ack(rtilePcieAdaptorTxRawIfc_dcrdt_init_ack),
        .rtilePcieAdaptorTxRawIfc_hdr       (rtilePcieAdaptorTxRawIfc_hdr),
        .rtilePcieAdaptorTxRawIfc_data      (rtilePcieAdaptorTxRawIfc_data),
        .rtilePcieAdaptorTxRawIfc_sop       (rtilePcieAdaptorTxRawIfc_sop),
        .rtilePcieAdaptorTxRawIfc_eop       (rtilePcieAdaptorTxRawIfc_eop),
        .rtilePcieAdaptorTxRawIfc_hvalid    (rtilePcieAdaptorTxRawIfc_hvalid),
        .rtilePcieAdaptorTxRawIfc_dvalid    (rtilePcieAdaptorTxRawIfc_dvalid),
        // TODO: FTile ports are surfaced on the wrapper top level for future
        // cocotb hookup. They are currently left for the testbench to drive
        // or observe and may remain floating in PCIe-only runs.
        .ftileMacAdaptorRxRawIfc_data       (ftileMacAdaptorRxRawIfc_data),
        .ftileMacAdaptorRxRawIfc_valid      (ftileMacAdaptorRxRawIfc_valid),
        .ftileMacAdaptorRxRawIfc_inframe    (ftileMacAdaptorRxRawIfc_inframe),
        .ftileMacAdaptorRxRawIfc_eop_empty  (ftileMacAdaptorRxRawIfc_eop_empty),
        .ftileMacAdaptorRxRawIfc_fcs_error  (ftileMacAdaptorRxRawIfc_fcs_error),
        .ftileMacAdaptorRxRawIfc_error      (ftileMacAdaptorRxRawIfc_error),
        .ftileMacAdaptorRxRawIfc_status_data(ftileMacAdaptorRxRawIfc_status_data),
        .ftileMacAdaptorRxRawIfc_ready      (ftileMacAdaptorRxRawIfc_ready),
        .ftileMacAdaptorTxRawIfc_ready      (ftileMacAdaptorTxRawIfc_ready),
        .ftileMacAdaptorTxRawIfc_data       (ftileMacAdaptorTxRawIfc_data),
        .ftileMacAdaptorTxRawIfc_valid      (ftileMacAdaptorTxRawIfc_valid),
        .ftileMacAdaptorTxRawIfc_inframe    (ftileMacAdaptorTxRawIfc_inframe),
        .ftileMacAdaptorTxRawIfc_eop_empty  (ftileMacAdaptorTxRawIfc_eop_empty),
        .ftileMacAdaptorTxRawIfc_error      (ftileMacAdaptorTxRawIfc_error),
        .ftileMacAdaptorTxRawIfc_skip_crc   (ftileMacAdaptorTxRawIfc_skip_crc)
    );

endmodule
